# version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/index.html:/usr/share/nginx/html/index.html
    depends_on:
      - express
  express:
    build:
      context: ./myproject
      dockerfile: Dockerfile
    container_name: express
    volumes:
      - ./myproject/data/users.json:/app/users.json
    expose:
      - "3000" 
